---
title: "Practical_Machine_Learning_Project"
output: html_document
---

##How the model was built

##cross validation

##expected out of sample error is

#Load Libraries
```{r}
library(RANN);library(rattle); library(caret); library(randomForest); library(rpart); library(rpart.plot); library(YaleToolkit)
```

#Pull Data
```{r}
trainUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training <- read.csv(url(trainUrl),na.strings=c("NA","#DIV/0!","","-","?"))
testing <- read.csv(url(testUrl),na.strings=c("NA","#DIV/0!","","-","?"))
```


```{r}
#Explore
head(training)
str(training)
ncol(training)
nrow(training)
colSums(is.na(training))
whatis(training) #theres a lot of variables with all N/A's, cvtd_timestamp has a lot of distinct values for a factor
unique(training$cvtd_timestamp) #ok this is ok
##featurePlot(x=training, y = training$classe, plot = "pairs")
```

#Data Slicing
Splitting Training Data into training and testing, on outcome classe
```{r}
inTrain <- createDataPartition(y=training$classe, p = .75, list = FALSE)
training<-training[inTrain,]; testing<-training[-inTrain,]
dim(training); dim(testing)
```

#Cleaning NA's and Near Zero Variances
```{r}
x = nearZeroVar(training, saveMetrics = TRUE)
str(x, vec.len=2)
x[x[,"zeroVar"] > 0, ]
x[x[,"zeroVar"] + x[,"nzv"] > 0, ]

naColumnVector<- c()
for (i in 1:ncol(training))
        if(sum(is.na(training[,i]))/nrow(training)>=.8)
                naColumnVector<-append(naColumnVector,i)
training <- training[,-(naColumnVector)]
```



#Training options
```{r}
args(trainControl)

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
